# Generated by Django 5.2.10 on 2026-01-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_failed_count_campaign_sent_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='total_recipient',
            new_name='total_recipients',
        ),
    ]
