# Generated by Django 5.2.10 on 2026-01-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_rename_total_recipient_campaign_total_recipients'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emaillogs',
            unique_together={('campaign', 'recipient_email')},
        ),
    ]
